server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue?characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:**/*.xml


logging:
  level:
    com:
      hand:
        sxy: DEBUG